import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CovidContextProvider } from "@/context/CovidContext";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Covid-19 Brasil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <CovidContextProvider>
          <Header />
          {children}
        </CovidContextProvider>
      </body>
    </html>
  );
}
